/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.connectdb;

/**
 *
 * @author Nguyen Viet Thinh
 */
public class ReturnBook extends javax.swing.JFrame {

    DefaultTableModel tbm = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    Connection conn;
    ResultSet  rs;
    PreparedStatement pst;
    static int key ;
    public ReturnBook(int x) {

        super("Return Book");
        key = x;
        initComponents();
        conn = connectdb.ConnecrDb();
        ShowDate();
        tableHandler handler = new tableHandler();
     jTable2.addMouseListener(handler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnRB = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBrS_RB = new javax.swing.JTextField();
        txtYrS_RB = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSName_RB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSeS_RB = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnSeS_RB = new javax.swing.JButton();
        txtSID_RB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBID = new javax.swing.JTextField();
        txtDateRB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Date of Return");

        btnRB.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\QuanLyNhaSach\\Icon\\icons8-return-book-16.png")); // NOI18N
        btnRB.setText("Return");
        btnRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRBActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\QuanLyNhaSach\\Icon\\icons8-go-back-16.png")); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153)), "Return Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Student_Name");

        txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt.setText("Student_ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Year");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Branch");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Semester");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        btnSeS_RB.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\QuanLyNhaSach\\Icon\\icons8-search-16.png")); // NOI18N
        btnSeS_RB.setText("Search");
        btnSeS_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeS_RBActionPerformed(evt);
            }
        });

        jLabel5.setText("Book_ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtYrS_RB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrS_RB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSName_RB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSID_RB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeS_RB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeS_RB)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(txtBID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt)
                    .addComponent(txtSID_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeS_RB)
                    .addComponent(jLabel5)
                    .addComponent(txtBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSName_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrS_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtYrS_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeS_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRB)
                        .addGap(37, 37, 37)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtDateRB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDateRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRB)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void LoadBrB(){
        tbm.setNumRows(0);
        int number;
        Vector row,column;
        column = new Vector();
        String sql = "SELECT b.* FROM `borrowbook`a,`book`b  WHERE a.`Book_ID` = b.`Book_ID` AND a.`Student_ID`=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSID_RB.getText());
            rs = pst.executeQuery();
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();//Trả về số cột
            
            for(int i= 1;i <= number;i++){
                column.add(metadata.getColumnName(i));//Lấy ra tiêu đề cho các cột
            }
            tbm.setColumnIdentifiers(column);
            while(rs.next()){
               
                row = new Vector();
                for(int i = 1; i<=number;i++){
                    row.addElement(rs.getString(i));
                }
                tbm.addRow(row);
                jTable2.setModel(tbm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    public void ShowDate(){
        txtDateRB.setEditable(false);
        Date date = new Date();
        
        txtDateRB.setText(sdf.format(date));
    }
    public int KTDate(){
        String sql = "SELECT `Date_Borrow` FROM `borrowbook` WHERE `Student_ID` =? AND`Book_ID`=?" ;
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSID_RB.getText());
            pst.setString(2, txtBID.getText());
            rs = pst.executeQuery();
            if(rs.next()){
            String date_br = rs.getString("Date_Borrow");
            
            
            Date d1 = null;
            Date d2 = null;
            Date currentDate = new Date();
            
                
                String endDate = sdf.format(currentDate);

                d1 = sdf.parse(date_br);
                d2 = sdf.parse(endDate);

                long getDiff = d2.getTime() - d1.getTime();

                long getDaysDiff = getDiff / (24 * 60 * 60 * 1000);
                
                if(getDaysDiff<30){
                    return 1;
                }
                else if(getDaysDiff>30){
                    return 0;
                }
             rs.close();
             pst.close();
            }
       } catch (Exception ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 2;
        
    }
    private void btnRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRBActionPerformed
        // TODO add your handling code here:
        if(KTDate() == 0){
         String sql = "INSERT INTO `returnbook`(`ID_RB`,`Student_ID`, `Book_ID`, `Date_Return`) VALUES (null,?,?,?)  ";
         
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSID_RB.getText());
            pst.setString(2, txtBID.getText());
            pst.setString(3, txtDateRB.getText());
            
            pst.execute();
            rs.close();
            pst.close();
            String sql1 = "DELETE FROM `borrowbook` WHERE `Student_ID`=? AND`Book_ID`=?";
            pst = conn.prepareStatement(sql1);
            pst.setString(1, txtSID_RB.getText());
            pst.setString(2, txtBID.getText());
            pst.execute();
            rs.close();
            pst.close();
            JOptionPane.showMessageDialog(null, "Trả sách quá hạn nên bị ăn 1 đấm !!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
      }
       else if(KTDate() == 1){
           String sql = "INSERT INTO `returnbook`(`Student_ID`, `Book_ID`, `Date_Return`) VALUES (?,?,?)  ";
         
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSID_RB.getText());
            pst.setString(2, txtBID.getText());
            pst.setString(3, txtDateRB.getText());
            
            pst.execute();
             rs.close();
             pst.close();
            String sql1 = "DELETE FROM `borrowbook` WHERE `Student_ID`=? AND `Book_ID`=?";
            pst = conn.prepareStatement(sql1);
            pst.setString(1, txtSID_RB.getText());
            pst.setString(2, txtBID.getText());
            pst.execute();
            rs.close();
                pst.close();
            JOptionPane.showMessageDialog(null, "Trả sách thành công !!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
      }
        LoadBrB();
    }//GEN-LAST:event_btnRBActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob = new Home(key);
        ob.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSeS_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeS_RBActionPerformed
        // TODO add your handling code here:
        LoadBrB();
        String sql ="SELECT b.* FROM `borrowbook`a,`student`b  WHERE a.`Student_ID` = b.`Student_ID` AND a.`Student_ID`=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSID_RB.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Name");
                txtSName_RB.setText(add1);
                String add2 = rs.getString("Branch");
                txtBrS_RB.setText(add2);
                String add3 = rs.getString("Year");
                txtYrS_RB.setText(add3);
                String add4 = rs.getString("Semester");
                txtSeS_RB.setText(add4);
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(null, "Mã học sinh không đúng nha!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnSeS_RBActionPerformed
    
    private class tableHandler extends MouseAdapter{
    public void mouseClicked(MouseEvent e) {
    if (e.getClickCount() == 1) {
      JTable target = (JTable)e.getSource();
      int row = target.getSelectedRow();
      int column = target.getSelectedColumn();
    txtBID.setText(tbm.getValueAt(row, 0).toString());
      
      // do some action if appropriate column
    }
  }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook(key).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRB;
    private javax.swing.JButton btnSeS_RB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtBID;
    private javax.swing.JTextField txtBrS_RB;
    private javax.swing.JTextField txtDateRB;
    private javax.swing.JTextField txtSID_RB;
    private javax.swing.JTextField txtSName_RB;
    private javax.swing.JTextField txtSeS_RB;
    private javax.swing.JTextField txtYrS_RB;
    // End of variables declaration//GEN-END:variables
}
